import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import MobileMenu from "@/components/mobile-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="min-h-full flex flex-col">
        <MobileMenu />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
